#!/snap/osmocom/current/bin/python3

import webview
import subprocess
import time

django = subprocess.Popen(
    ["/snap/osmocom/current/bin/python3",
     "/snap/osmocom/current/osmo-gui/manage.py",
     "runserver", "127.0.0.1:8900"], )
time.sleep(0.5)
webview.create_window(
    "Osmocom",
    "http://localhost:8900/hlr/",
    text_select= True,
    width=1366,
    height=768,
    min_size=(800, 600)  
)
webview.start()
django.terminate()

if __name__ == "__main__":
    pass