name: osmocom
version: 1.0.0
summary: A graphical user interface for the Osmocom project
description: |
  This is the graphical user interface for the Osmocom project.
  This program is developed with Django framework. 
  It is a web application that allows to manage the Osmocom network.
  However, it is not a complete web application.
confinement: devmode
base: core22
grade: devel

parts:
  osmocom:
    plugin: python
    source: .

    build-packages:
      - gcc
      - pkg-config
      - python3-dev
      - build-essential
      - libxml2-dev
      - libcurl4-openssl-dev
      - libicu-dev

    stage-packages:
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - gir1.2-webkit2-4.0
      - gir1.2-ibus-1.0
      - gobject-introspection

    python-packages:
      - django
      - pywebview
      - pycairo
      - pygobject

    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/osmo-gui
      cp -r * $SNAPCRAFT_PART_INSTALL/osmo-gui
      mv $SNAPCRAFT_PART_INSTALL/osmo-gui/gui $SNAPCRAFT_PART_INSTALL/run-program
      chmod +x $SNAPCRAFT_PART_INSTALL/run-program
      snapcraftctl build

apps:
  osmocom:
    command: run-program
    plugs: [network]
